# Generated by Django 5.1.7 on 2025-04-13 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_ordering', '0003_remove_orderitem_subtotal_order_is_complete_and_more'),
    ]

    operations = [
    ]
