# Generated by Django 5.2 on 2025-04-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_ordering', '0004_auto_20250413_1215'),
    ]

    operations = [
    ]
